# Copyright (c) {{ cookiecutter.Year }}-present, {{ cookiecutter.Copyright_holder }}.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

cxx_binary(
  name = 'main',
  srcs = glob(['*.cc', '*.cpp', '*.cxx']),
  deps = [
    '//src:{{ cookiecutter.Library_name }}',
  ]
)
