# Copyright (c) {{ cookiecutter.Year }}-present, {{ cookiecutter.Copyright_holder }}.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

sh_binary(
    name = "lint",
    main = "style.sh"
)

sh_binary(
    name = "doc",
    main = "doc.sh"
)
