# Copyright (c) {{ cookiecutter.Year }}-present, {{ cookiecutter.Copyright_holder }}.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

android_library(
  name = 'solib',
  srcs = glob(['*.java']),
  deps = [
    '//samples/android/resources:res',
    '//samples/android/cxx:{{ cookiecutter.Library_name }}jni',
  ],
  visibility = [
    '//samples/android:CppLibCallerApp',
  ],
)
